### ISSUE TITLE
Doesn´t work in Bludit

### ISSUE THREAD

**Issue by mr-greystark** [bludit-plugins/tail.writer#1]
I have an error when i install this plugin in a Clean bludit 3.7.1 Installation.
The editor doesn´t work.

![image](https://user-images.githubusercontent.com/18200419/52904918-3f56d980-3211-11e9-9db1-03dce1b10859.png)

The chrome explorer show this.

Uncaught TypeError: Cannot read property 'replace' of undefined
    at d.indenter (tail.writer.min.js:2)
    at d.read (tail.writer.min.js:2)
    at d.build (tail.writer.min.js:2)
    at new d (tail.writer.min.js:2)
    at Object.d [as writer] (tail.writer.min.js:2)
    at HTMLDocument.<anonymous> (new-content:762)

![image](https://user-images.githubusercontent.com/18200419/52904876-b0e25800-3210-11e9-9872-fc21de8a2a79.png)

I have try solve this problem, but i dont know how works this plugin

Thanks for this proyect!

**Comment by dignajar** [comment]
Maybe you have other editor enabled ? Such as Tinymce or Simplemde ?
I will check.

**Comment by mr-greystark** [comment]
Yes, i do. 
First, I tried to install this editor in my modified version of Bludit, but it didn´t work.
So I thought maybe I broke bludit. 
I decided to install a clean version of Bludit (3.7.1), disabled the two editors and installed the plugin, but it didn´t work either

**Comment by mr-greystark** [comment]
Yes, i do. 
First, I tried to install this editor in my modified version of Bludit, but it didn´t work.
So I thought maybe I broke bludit. I decided to install a clean version of Bludit (2.7.3), disable the two editors and install the plugin, but it didn´t work either

**Comment by mr-greystark** [comment]
Yes, i do.
First, I tried to install this editor in my modified version of Bludit, but it didn´t work.
So I thought maybe I broke bludit. I decided to install a clean version of Bludit (3.7.1), disable the two editors and install the plugin, but it didn´t work either

**Comment by SamBrishes** [comment]
Hellow, 

sorry for the long wait! I created a Hotfix for your issue, check out [this version](https://github.com/pytesNET/tail.writer-bludit), it should work.

Thanks for reporting.

Sincerely,
Sam.

**Comment by dignajar** [comment]
@SamBrishes do you want to keep the plugin in your repository ? for me is ok and maybe better to improve it by your self.

**Comment by mr-greystark** [comment]
ok, I tested the plugin in a Clean Bludit. 
Now I see the editor, but it´s not possible to write on it.

![image](https://user-images.githubusercontent.com/18200419/52912848-17f62000-3296-11e9-90ba-12a8f7a2403b.png)

![image](https://user-images.githubusercontent.com/18200419/52912864-3bb96600-3296-11e9-89b6-1319ea9f2b5f.png)

![image](https://user-images.githubusercontent.com/18200419/52912876-5ee41580-3296-11e9-9600-c14d25b107eb.png)

**Comment by SamBrishes** [comment]
Hellow,

after a few minutes of checking, I found the main reason for the current incompatibility. The tail.writer system isn't hooked to a `textarea` HTML element. So it couldn't use the textarea typical functions and variables.

Now it is fixed finally, [download it here](https://github.com/pytesNET/tail.writer-bludit) and test it. I could successfully write and store data using Chrome and Firefox and Bludit 3.7.1.

I'm really sorry for this, I didn't noticed, that bludit doesn't use a textarea field per default, si I had to create my own one.

Sincerely,
Sam.

**Comment by mr-greystark** [comment]
Dont worry @SamBrishes, your final work its awesome! 
Everything its working.

Thanks a lot.
Ignacio.

**Comment by SamBrishes** [comment]
Perfect and thanks. :D 

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
> @SamBrishes do you want to keep the plugin in your repository ? for me is ok and maybe better to improve it by your self.

Hellow @dignajar.

Okay, if you want I can also keep the plugin on my repository and maintain it directly. ^^

Sincerely,
Sam.

**Comment by dignajar** [comment]
Yes I prefer that, I will change the plugin repo. https://github.com/bludit/plugins-repository/tree/master/items/tail-writer

and point to your repo, the release you did has the fixes ?

**Comment by SamBrishes** [comment]
Okay, thanks. And yes, my release has all respective fixes.
